---

- name:  Install open jdk-8 on the target
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: yes

- name:  Add JAVA_HOME to profile
  shell: echo 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk' | sudo tee -a /etc/profile

- name:  Add JRE_HOME to profile
  shell: echo 'export JRE_HOME=/usr/lib/jvm/jre' | sudo tee -a /etc/profile

- name:  Making /etc/profile active
  shell: source /etc/profile
