---
- name: Find OS flavour
  shell: cat /etc/*-release | grep ^NAME | awk -F = '{ print $2 }' |  sed 's/"//g'
  register: flavour

- name: Install latest nginx on Ubuntu
  apt:
   name: nginx
   state: latest
   update_cache: yes
  when: flavour.stdout == "Ubuntu"

- name: Install latest nginx on CentOS
  yum:
   name: nginx
   state: latest
  when: flavour.stdout == "CentOS Linux"

- name: Stop nginx service
  service: 
   name: nginx 
   state: stopped
  ignore_errors: yes

- name: Create directories for site enabled and available
  file: path=/etc/nginx/sites-enabled state=directory
  when: flavour.stdout == "CentOS Linux"

- name: Create directories for site enabled and available
  file: path=/etc/nginx/sites-available state=directory
  when: flavour.stdout == "CentOS Linux"

- name: Remove default config files
  file: path=/etc/nginx/{{ item }} state=absent
  with_items:
   - nginx.conf

- name: Add custom config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  when: flavour.stdout == "CentOS Linux"

- name: Creating directories for the sites
  command: mkdir -p /usr/share/nginx/{{ item }}/html
  with_items:
   - myfirstpage.com
   - mysecondpage.com
   - mythirdpage.com
  when: flavour.stdout == "CentOS Linux"

- name: Copy the HTML files
  copy: src=1.html dest=/usr/share/nginx/myfirstpage.com/html/1.html
- copy: src=2.html dest=/usr/share/nginx/mysecondpage.com/html/2.html
- copy: src=3.html dest=/usr/share/nginx/mythirdpage.com/html/3.html

- name: Copy the sites config
  copy: src=myfirstpage.com.conf dest=/etc/nginx/sites-available/myfirstpage.com.conf
- copy: src=mysecondpage.com.conf dest=/etc/nginx/sites-available/mysecondpage.com.conf
- copy: src=mythirdpage.com.conf dest=/etc/nginx/sites-available/mythirdpage.com.conf

- name: Enabling the sites
  command: ln -s /etc/nginx/sites-available/{{ item }} /etc/nginx/sites-enabled/
  with_items:
   - myfirstpage.com.conf
   - mysecondpage.com.conf
   - mythirdpage.com.conf
  ignore_errors: true

- name: Start nginx service
  service: state=restarted name=nginx
